/* Autogenerated by png2wx.pl on Thu Oct 29 12:01:00 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_plots;

#ifdef PLOTS_USE_SVG
extern wxString _svg_plots;
extern wxString _svg_plots_rollover;
extern wxString _svg_plots_toggled;
#endif

#endif /* ICONS_H */
