/* Autogenerated by png2wx.pl on Sat Feb 21 11:34:32 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_trimplot;

#endif /* ICONS_H */
